// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fxlghypwmzbywpgdnwwd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4bGdoeXB3bXpieXdwZ2Rud3dkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwOTQ2MDMsImV4cCI6MjA3MDY3MDYwM30.ya9q-FW6-KARxa19Lfh9LlMV-OZGcM-x2wLo7IUiyrU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});